_target_: 'gcpc.model.mlp.MLPPolicyLM'
env_name: ???
obs_dim: ???
action_dim: ???
goal_dim: ???
ctx_size: ???
future_horizon: ???
epochs: ???
lr: ???
seed: ???
eval_last_k: ???
num_eval_rollouts: ???
goal_type: ???
model_config:
  embed_dim: 1024
  pdrop: 0