defaults:
  - _self_
  - model: trajnet
  - exp: pick_trl
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

wandb:
  project: "ail-mk2"

hydra:
  output_subdir: null
  run:
    dir: .

seed: 1

env_name: FetchPick-v0
traj_load_path: ./expert_datasets/pick_10000.pt
devices: [0]
num_workers: 8
train_size: 0.9
opts: 0.0
info: ''

