# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

project: 'drail-project'
program: drail/main.py
method: grid
name: Walker-iq-5traj

parameters:
  seed:
    # values: [1, 2, 3, 4, 5]
    value: 1
  prefix:
    value: "iqlearn"
  alg:
    value: "iq-learn"
  traj-load-path:
    value: ./expert_datasets/ppo_walker_5.pt
  env-name:
    value: "Walker2d-v3"
  normalize-env:
    value: True
  eval-num-processes:
    value: 10
  cuda:
    value: True
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 100
  lr:
    values: [0.000001]
  log-interval:
    value: 1000
  save-interval:
    value: 100000
  eval-interval:
    value: 1000
  clip-actions:
    value: True
  gamma:
    value: 0.99
  divergence:
    value: 'kl'
  sample:
    value: 'value_expert'
  grad-pen:
    value: False
  regularize:
    value: False
  actor-update-freq:
    value: 1
  critic-target-update-freq:
    # values: [1, 2]
    value: 2
  offline:
    value: False
  num-actor-updates:
    value: 1
  critic-lr:
    value: 1e-4
  alpha-lr:
    value: 1e-4
  init-temperature:
    value: 0.01
  learnable-temp:
    value: True
  tau: 
    value: 0.005
  num-env-steps:
    value: 2000000