# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

project: 'drail-project'
program: drail/main.py
method: grid
name: Push-bc-1.25
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  seed:
    values: [1, 2, 3, 4, 5]
    # value: 2
  prefix:
    value: "bc"
  alg:
    value: "bc"
  traj-load-path:
    value: "./expert_datasets/push_partial2.pt"
  env-name:
    value: "FetchPushEnvCustom-v0"
  normalize-env:
    value: False
  cuda:
    value: True
  eval-num-processes:
    value: 10
  num-render:
    value: 0
  num-eval:
    value: 10
  vid-fps:
    value: 60
  log-interval:
    value: 1
  save-interval:
    value: 100000
  eval-interval:
    value: 200
  bc-num-epochs:
    value: 1000
  traj-val-ratio:
    value: 0.2
  lr:
    # values: [0.0002, 0.0001, 0.00005]
    value: 0.0002
  noise-ratio:
    value: 1.25
  goal-noise-ratio:
    value: 1.25
