defaults:
  - _self_
  - model: trajnet
  - exp: antmaze_trl
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

wandb:
  project: "gcpc"

hydra:
  output_subdir: null  
  run:  
    dir: .

seed: 1

env_name: ???  # specified later
# max_episode_length: 1001
devices: [0]
num_workers: 8
train_size: 0.9
eval_last_k: 5
info: ''

