project: 'gcpc-project'
program: gcpc/main.py
method: grid
name: Pick-GCPC-0.00
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits

parameters:
  prefix:
    value: gcpc
  alg:
    value: gcpc
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0
  eval-num-processes:
    value: 1
  num-render:
    value: 1
  num-eval:
    value: 100
  eval-interval:
    value: 500
  save-interval:
    value: 1000
  traj-val-ratio:
    value: 0
  traj-load-path:
    value: ./expert_datasets/pick_10000.pt
  normalize-env:
    value: False
  gcpc-num-epochs:
    value: 1000
  lr:
    value: 0.0008
  depth:
    value: 3
  num-env-steps:
    value: 25000000
  goal-noise-ratio:
    value: 1.0
  noise-ratio:
    value: 1.0
  seed:
    values: [1,2,3,4,5]
  ctx-size:
    value: 4
  mae-ckpt-path:
    value: ./lightning_logs/FetchPick-v0/trajnet-opts:0.0/checkpoints/last.ckpt