project: 'gcpc-project'
program: gcpc/main.py
method: grid
name: Ant-GCPC-0.00
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
  
parameters:
  prefix:
    value: gcpc
  alg:
    value: gcpc
  env-name:
    value: AntGoal-v0
  normalize-env:
    value: False
  traj-load-path:
    value: ./expert_datasets/ant_50.pt
  gcpc-num-epochs:
    value: 1000
  eval-num-processes:
    value: 20
  ant-noise:
    value: 0.0
  traj-frac:
    value: 0.5
  traj-val-ratio:
    value: 0.2
  seed:
    values: [1,2,3,4,5]
  ctx-size:
    value: 4
  mae-ckpt-path:
    value: ./lightning_logs/AntGoal-v0/trajnet-opts:0.0/checkpoints/last.ckpt